### ISSUE TITLE
Sparse regression example no longer working

### ISSUE THREAD

**Issue by patwa67** [JuliaFirstOrder/ProximalAlgorithms.jl#77] opened 2022-03-15 21:07 UTC
I get an error when I try to run the Sparse Regression example in the documentation:
UndefVarError: FastForwardBackward not defined
getproperty(x::Module, f::Symbol) at Base.jl:35
top-level scope at ProxAlgLASSO.jl:47
eval at boot.jl:373 [inlined]

**Comment by lostella** [comment] 2022-03-15 22:07
@patwa67 are you sure you have the latest version of the package installed (0.5.0 or newer)? Running `] st ProximalAlgorithms` from the REPL, in the environment you're using, should reveal it.

I can access `FastForwardBackward` without issues (I have 0.5.3):

```julia
julia> using ProximalAlgorithms

julia> ProximalAlgorithms.FastForwardBackward
FastForwardBackward (generic function with 1 method)
```

**Comment by lostella** [comment] 2022-03-16 09:08
You probably installed this in an environment where ProximalAlgorithms is constrained to <0.5 then (by some package depending on it: maybe StructuredOptimization?)

I suggest you try in a fresh environment, that should work.

**Comment by patwa67** [comment] 2022-03-16 09:10
Yes I have StructuredOptimization installed. So the only way is to delete that one?

**Comment by lostella** [comment] 2022-03-16 09:13
It depends on what you need to do: StructuredOptimization is only compatible with ProximalAlgorithms < 0.5 at the moment (I’m not sure when/if it will updated, as I currently don’t have capacity for maintainance there).

If you want to try out the latest ProximalAlgorithms 0.5, then I suggest you do this in a new environment, where you can install its latest version (and not have StructuredOptimization at all there).

**Comment by patwa67** [comment] 2022-03-16 09:19
I'm having problems that gamma becomes too low so I would very much like to try the minimum_gamma option. And this was not possible with earlier versions.

**Comment by lostella** [comment] 2022-03-16 09:23
I see. Is there any way you can formulate your problem directly for ProximalAlgorithms to consume, without going through StructuredOptimization? That I think would be the best attempt at validating what the issue is, whether it was fixed with earlier versions, or anything.

If the problem still persists with that, feel free to open a separate dedicated issue (this one appears to be resolved).

**Comment by lostella** [comment] 2022-03-16 09:41
Could you provide self-contained code snippet that generates the error? With minimal data that is (some small matrix, even random stuff)

**Comment by patwa67** [comment] 2022-03-16 09:42
It is your Sparse Regression example in the documentation, straight off.

**Comment by patwa67** [comment] 2022-03-16 09:47
Aha, it turned out that I had an old version of ProximalOperators also. Is it so that StucturedOptimization holds that one back also? Maybe some warnings regarding this. Anyway, the example works now.

**Closed** 2022-03-16 09:57 UTC
Labels: cannot reproduce

**Comment by lostella** [comment] 2022-03-16 11:39
Ha! True, that’s a hard one to spot! Not sure how to best give a warning about this, given that there’s no dependency between the packages now.

Definitely some hint in the documentation though. I’ll open an issue for that, it should be made clear.

Anyhow, happy that things worked out
